---
title: "Assignment 1: Introduction"
author: "Blair Johnson"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1. Change "Student Name" on line 3 (above) with your name.
3. Work through the steps, **creating code and output** that fulfill each instruction.
4. Be sure to **answer the questions** in this assignment document.
6. When you have completed the assignment, **Knit** the text and code into a single PDF file.
8. After Knitting, submit the completed exercise (PDF file) to the dropbox in Sakai. Add your last name into the file name (e.g., "Lima_A01_Introduction.Rmd") prior to submission.

The completed exercise is due on <>.

## 1) Discussion Questions

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I have had some experience in data analytics and R through taking ENVIRON 710 in Fall of 2020. I have some experience using R to solve statistics problems, handle large datasets, and use statistical models. I also had some practice with R in my summer internship where I analyzed datasets pertaining to Clean Water State Revolving Fund projects. I have never used Git but look forward to learning how to use the software. 

2. Are there any components of the course about which you feel confident?

> Answer: I feel pretty confident about data visualizations and plots through ggplot. I am also fairly confident with data wrangling and importing. 

3. Are there any components of the course about which you feel apprehensive?

> Answer: Not at the moment, but I do want to learn how I can troubleshoot R issues more effectively. I have also had zero GitHub experience so I feel that learning to incorporate GitHub and R will take some practice. 


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository  and that you have updated your course README file. 

> Answer: 
https://github.com/bsj16/Environmental_Data_Analytics_2022

